---
name: eInnsyn poller
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: script
        run: bash runCurl.sh
